# Generated by Django 5.0.3 on 2024-04-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('publication_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('borrowingId', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreManager.book')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreManager.member')),
            ],
        ),
    ]
