# Generated by Django 5.0.3 on 2024-04-04 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookStoreManager.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Author ID'),
        ),
    ]
