# Generated by Django 5.0.4 on 2024-04-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreManager', '0002_book_authorid_alter_author_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='boobkCover',
            field=models.ImageField(null=True, upload_to='bookCovers/'),
        ),
    ]
